[package]
name = "nobox-wayland"
description = "Experimental native Wayland compositor backend for nobox"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version = "0.2.36"

[dependencies]
anyhow.workspace = true
clap.workspace = true
fontdb.workspace = true
fontdue.workspace = true
nobox-core.workspace = true
nobox-config.workspace = true
nobox-runtime.workspace = true
nobox-desktop.workspace = true
rustix.workspace = true
smithay.workspace = true
smithay-drm-extras.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
wayland-client = "0.31.10"
wayland-protocols.workspace = true
wayland-protocols-misc.workspace = true
wayland-protocols-wlr.workspace = true
x11rb.workspace = true

[[bin]]
name = "nobox-wayland-probe"
path = "src/bin/probe.rs"
test = false

[lints]
workspace = true
